# <span style="color:red"> Lecture 17: Pandas Operations and Data Manipulation </span>

<font size = "4">

Topics we should be familiar up to this point:

- **Object Types**: int, float, str, lists, arrays,<br>
booleans, pandas dataframes


- If/else statements and loops

- Functions (both built-in and user defined)

If there are any of these topics you need help <br>
 understanding, don't be afraid to come to office hours!

<font size = "4">

This lecture:

- We will take a closer look at the `Pandas` library

- A lot of new object types and functions/methods

- We should keep the basic programming ideas listed above in mind

## <span style="color:red"> I. Import Libraries and Read in Files</span>

In [47]:
import pandas as pd
import matplotlib.pyplot as plt

<font size = "4">

**Q:** How should I load in the "features.csv" file inside the data_raw folder?

In [48]:
# Read in the car features dataset

carfeatures = pd.read_csv("data_raw/subfolder1/annoying_subfolder/features.csv")

In [49]:
# what if I want to read in data from Lecture_16_OOP__Class_Variables_and_Inheritance/data/greendale_students.csv???

gd_student = pd.read_csv("../Lecture_16_OOP__Class_Variables_and_Inheritance/data/greendale_students.csv")

<font size = "4">

Often a good idea to verify the **type** of a variable

In [50]:
type(carfeatures)

pandas.DataFrame

<font size = "4">

- The type is "pandas.core.frame.DataFrame". 

    - It's a reasonable rule of thumb to only pay attention to the first and last phrases of a datatype like this.

    - So `carfeatures` is a "Pandas DataFrame" object

- You might also want to print the variable itself

In [51]:
print(carfeatures)

      mpg  cylinders  displacement horsepower  weight  acceleration vehicle_id
0    18.0          8           307        130    3504          12.0  C-1689780
1    15.0          8           350        165    3693          11.5  B-1689791
2    18.0          8           318        150    3436          11.0  P-1689802
3    16.0          8           304        150    3433          12.0  A-1689813
4    17.0          8           302        140    3449          10.5  F-1689824
..    ...        ...           ...        ...     ...           ...        ...
393  27.0          4           140         86    2790          15.6  F-1694103
394  44.0          4            97         52    2130          24.6  V-1694114
395  32.0          4           135         84    2295          11.6  D-1694125
396  28.0          4           120         79    2625          18.6  F-1694136
397  31.0          4           119         82    2720          19.4  C-1694147

[398 rows x 7 columns]

In [52]:
display(carfeatures)

      mpg  cylinders  displacement horsepower  weight  acceleration vehicle_id
0    18.0          8           307        130    3504          12.0  C-1689780
1    15.0          8           350        165    3693          11.5  B-1689791
2    18.0          8           318        150    3436          11.0  P-1689802
3    16.0          8           304        150    3433          12.0  A-1689813
4    17.0          8           302        140    3449          10.5  F-1689824
..    ...        ...           ...        ...     ...           ...        ...
393  27.0          4           140         86    2790          15.6  F-1694103
394  44.0          4            97         52    2130          24.6  V-1694114
395  32.0          4           135         84    2295          11.6  D-1694125
396  28.0          4           120         79    2625          18.6  F-1694136
397  31.0          4           119         82    2720          19.4  C-1694147

[398 rows x 7 columns]

<font size = "4">

Or you can view variables by going to the "Jupyter Variables" tab at the top of the notebook. Then click on the icon to the left of `carfeatures` to open it in Data Wrangler.

<font size = "4">

Alternatively, you can also print out just the first 5 rows of `carfeatures`.

In [53]:
print(carfeatures.head())

    mpg  cylinders  displacement horsepower  weight  acceleration vehicle_id
0  18.0          8           307        130    3504          12.0  C-1689780
1  15.0          8           350        165    3693          11.5  B-1689791
2  18.0          8           318        150    3436          11.0  P-1689802
3  16.0          8           304        150    3433          12.0  A-1689813
4  17.0          8           302        140    3449          10.5  F-1689824

<font size = "4">

Or the first 7 rows:

In [54]:
display(carfeatures.head(7))

    mpg  cylinders  displacement horsepower  weight  acceleration vehicle_id
0  18.0          8           307        130    3504          12.0  C-1689780
1  15.0          8           350        165    3693          11.5  B-1689791
2  18.0          8           318        150    3436          11.0  P-1689802
3  16.0          8           304        150    3433          12.0  A-1689813
4  17.0          8           302        140    3449          10.5  F-1689824
5  15.0          8           429        198    4341          10.0  F-1689835
6  14.0          8           454        220    4354           9.0  C-1689846

<font size = "4">

**Note:** `.head()` is a *method* which is just a function that "belongs" to an object.

<font size = "4">


**Exercise (Coffee):** Read `data_raw/exercise_data/indonesia_coffee_chain_wars_enriched_2026.csv` into a variable `coffee` and display the first 10 rows.

In [55]:
# your answer here

coffee = pd.read_csv("data_raw/exercise_data/indonesia_coffee_chain_wars_enriched_2026.csv")

display(coffee.head(10))

,store_transaction_id,coffee_brand,city_location,store_format,competitor_density_500m,base_price_idr,discount_voucher_pct,order_method,daily_cups_sold,customer_review_rating,...,revenue_per_competitor_density,price_competitiveness_ratio,dwell_time_to_spend_ratio,cannibalization_risk_index,customer_price_sensitivity_score,outlet_operating_margin_estimate_pct,customer_brand_loyalty_tier,primary_brand_switch_driver,cot_retail_dynamics_rationale,confidence_score
0,ID_COF_04E8960997,Fore Coffee,Bali Badung,Mall Kiosk,2,31000,31.0,Dine-In POS Cashier,489,5.0,...,3486570.0,1.086,6.45,4.02,5.92,21.2,Promo-Chaser-Opportunist,Cheaper-Competitor-Opening,Gerai/transaksi 'ID_COF_04E8960997' dari jarin...,0.962
1,ID_COF_11C2B7E56B,Fore Coffee,Bali Badung,Standalone Shophouse / Ruko,0,35000,22.1,Mobile App Pickup,518,4.0,...,14123270.0,1.384,0.51,3.15,3.29,30.3,Value-Conscious-Regular,Taste-Inconsistency-Drop,Gerai/transaksi 'ID_COF_11C2B7E56B' dari jarin...,0.989
2,ID_COF_13E6C4B1C1,Fore Coffee,Bali Badung,Standalone Shophouse / Ruko,7,29000,29.1,Online Ojol Delivery,382,5.0,...,981788.0,1.044,0.49,5.85,3.65,27.8,Value-Conscious-Regular,Cheaper-Competitor-Opening,Gerai/transaksi 'ID_COF_13E6C4B1C1' dari jarin...,0.966
3,ID_COF_173255A861,Fore Coffee,Bali Badung,Standalone Shophouse / Ruko,2,27000,18.4,Dine-In POS Cashier,344,4.5,...,2526336.0,1.118,0.68,3.68,5.08,31.6,Value-Conscious-Regular,Lack-Of-Seating-WiFi,Gerai/transaksi 'ID_COF_173255A861' dari jarin...,0.984
4,ID_COF_26F9915A2A,Fore Coffee,Bali Badung,Office Tower Lobby,2,32000,14.4,Online Ojol Delivery,489,4.5,...,4464896.0,1.391,0.26,3.11,2.04,29.0,Die-Hard-Loyalist,Voucher-Exhaustion-Price-Hike,Gerai/transaksi 'ID_COF_26F9915A2A' dari jarin...,0.951
5,ID_COF_2BF33944D9,Fore Coffee,Bali Badung,Standalone Shophouse / Ruko,6,28000,15.4,Online Ojol Delivery,456,4.0,...,1543104.0,1.203,0.42,4.92,3.12,32.6,Value-Conscious-Regular,Taste-Inconsistency-Drop,Gerai/transaksi 'ID_COF_2BF33944D9' dari jarin...,0.946
6,ID_COF_2E5968D54E,Fore Coffee,Bali Badung,Office Tower Lobby,5,24000,25.9,Mobile App Pickup,432,5.0,...,1280448.0,0.903,0.62,4.63,3.93,24.9,Value-Conscious-Regular,Cheaper-Competitor-Opening,Gerai/transaksi 'ID_COF_2E5968D54E' dari jarin...,0.988
7,ID_COF_2EA2B79D3A,Fore Coffee,Bali Badung,Drive-Thru Highway,0,28000,38.8,Online Ojol Delivery,170,5.0,...,2913120.0,0.870,0.41,2.27,5.60,25.4,Promo-Chaser-Opportunist,Cheaper-Competitor-Opening,Gerai/transaksi 'ID_COF_2EA2B79D3A' dari jarin...,0.990
8,ID_COF_2EAFCC4543,Fore Coffee,Bali Badung,Mall Kiosk,1,26000,34.4,Online Ojol Delivery,435,4.5,...,3709680.0,0.866,0.47,3.82,4.55,20.0,Promo-Chaser-Opportunist,Cheaper-Competitor-Opening,Gerai/transaksi 'ID_COF_2EAFCC4543' dari jarin...,0.990
9,ID_COF_2EE2584DD6,Fore Coffee,Bali Badung,Standalone Shophouse / Ruko,5,26000,39.1,Online Ojol Delivery,478,5.0,...,1261442.0,0.804,0.44,5.60,5.03,24.3,Promo-Chaser-Opportunist,Cheaper-Competitor-Opening,Gerai/transaksi 'ID_COF_2EE2584DD6' dari jarin...,0.990

<font size = "4">

**Exercise (Chess):** Read `data_raw/exercise_data/magnus_carlsen_all_online_games_cleaned.csv` into `carlsen` and print the first 5 rows.

In [56]:
# your answer here

carlsen = pd.read_csv("data_raw/exercise_data/magnus_carlsen_all_online_games_cleaned.csv")

display(carlsen.head())

,opponent_color,opponent_name,opponent_rating,player_color,player_name,player_rating,result,result_raw,year,date,format,moves
0,black,RainnWilson,1200.0,white,Magnus Carlsen,2862,Win,1-0,2014,2014-12-14,Rapid,1. e4 g6 2. Nf3 d6 3. d4 Bg7 4. Bc4 Bg4 5. Bxf...
1,black,solskytz,1702.0,white,Magnus Carlsen,2862,Win,1-0,2014,2014-12-14,Rapid,1. d4 Nf6 2. c4 e6 3. Nc3 Bb4 4. e3 c5 5. Ne2 ...
2,black,Tildenbeatsu,1200.0,white,Magnus Carlsen,2862,Win,1-0,2014,2014-12-14,Rapid,1. e4 e5 2. Nf3 Nc6 3. Bb5 Nf6 4. O-O Nxe4 5. ...
3,black,mtmnfy,1200.0,white,Magnus Carlsen,2862,Win,1-0,2014,2014-12-14,Rapid,1. d4 e6 2. e4 d5 3. Nd2 Nc6 4. Ngf3 Nf6 5. e5...
4,black,stepanosinovsky,2360.0,white,Magnus Carlsen,2862,Loss,0-1,2014,2014-12-14,Rapid,1. d4 Nf6 2. Bg5 c5 3. d5 Ne4 4. Bc1 e6 5. c4 ...

<font size = "4">

**Exercise (Netflix):** Read `data_raw/exercise_data/netflix_titles.csv` into `netflix` and print it.

In [57]:
# your answer here
netflix = pd.read_csv("data_raw/exercise_data/netflix_titles.csv")

print(netflix)

     show_id     type                  title         director  \
0         s1    Movie   Dick Johnson Is Dead  Kirsten Johnson
1         s2  TV Show          Blood & Water              NaN
2         s3  TV Show              Ganglands  Julien Leclercq
3         s4  TV Show  Jailbirds New Orleans              NaN
4         s5  TV Show           Kota Factory              NaN
...      ...      ...                    ...              ...
8802   s8803    Movie                 Zodiac    David Fincher
8803   s8804  TV Show            Zombie Dumb              NaN
8804   s8805    Movie             Zombieland  Ruben Fleischer
8805   s8806    Movie                   Zoom     Peter Hewitt
8806   s8807    Movie                 Zubaan      Mozez Singh

                                                   cast        country  \
0                                                   NaN  United States
1     Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...   South Africa
2     Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...            NaN
3                                                   NaN            NaN
4     Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...          India
...                                                 ...            ...
8802  Mark Ruffalo, Jake Gyllenhaal, Robert Downey J...  United States
8803                                                NaN            NaN
8804  Jesse Eisenberg, Woody Harrelson, Emma Stone, ...  United States
8805  Tim Allen, Courteney Cox, Chevy Chase, Kate Ma...  United States
8806  Vicky Kaushal, Sarah-Jane Dias, Raaghav Chanan...          India

              date_added  release_year rating   duration  \
0     September 25, 2021          2020  PG-13     90 min
1     September 24, 2021          2021  TV-MA  2 Seasons
2     September 24, 2021          2021  TV-MA   1 Season
3     September 24, 2021          2021  TV-MA   1 Season
4     September 24, 2021          2021  TV-MA  2 Seasons
...                  ...           ...    ...        ...
8802   November 20, 2019          2007      R    158 min
8803        July 1, 2019          2018  TV-Y7  2 Seasons
8804    November 1, 2019          2009      R     88 min
8805    January 11, 2020          2006     PG     88 min
8806       March 2, 2019          2015  TV-14    111 min

                                              listed_in  \
0                                         Documentaries
1       International TV Shows, TV Dramas, TV Mysteries
2     Crime TV Shows, International TV Shows, TV Act...
3                                Docuseries, Reality TV
4     International TV Shows, Romantic TV Shows, TV ...
...                                                 ...
8802                     Cult Movies, Dramas, Thrillers
8803             Kids' TV, Korean TV Shows, TV Comedies
8804                            Comedies, Horror Movies
8805                 Children & Family Movies, Comedies
8806     Dramas, International Movies, Music & Musicals

                                            description
0     As her father nears the end of his life, filmm...
1     After crossing paths at a party, a Cape Town t...
2     To protect his family from a powerful drug lor...
3     Feuds, flirtations and toilet talk go down amo...
4     In a city of coaching centers known to train I...
...                                                 ...
8802  A political cartoonist, a crime reporter and a...
8803  While living alone in a spooky town, a young g...
8804  Looking to survive in a world taken over by zo...
8805  Dragged from civilian life, a former superhero...
8806  A scrappy but poor boy worms his way into a ty...

[8807 rows x 12 columns]

<font size = "4">


**Exercise (Social Media):** Read `data_raw/exercise_data/Social_media_impact_on_life.csv` into `social` and display the first 2 rows.

In [58]:
# your answer here

social = pd.read_csv("data_raw/exercise_data/Social_media_impact_on_life.csv")

display(social.head(2))

,Student_ID,Age,Gender,Academic_Level,Primary_Platform,Daily_Usage_Hours,Weekend_Extra_Hours,Device_Type,Sleep_Duration_Hours,Sleep_Quality_Score,Late_Night_Usage,Social_Comparison_Frequency,Perceived_Stress_Score,Mental_Health_Index,Academic_Performance_GPA,Overall_Impact
0,STU_2024000,19,Female,Undergraduate,Snapchat,7.5,1.5,Smartphone,5.9,2,True,Always,20.0,73,2.73,Neutral
1,STU_2024001,19,Female,Undergraduate,Instagram,4.6,1.3,Smartphone,7.9,3,True,Sometimes,17.0,90,3.21,Beneficial

## <span style="color:red"> II. Extract column/variable names </span>

<font size = "4">

In Homework #2, you manually created a list of column names. We saw in Quiz #1 that you can access the column names as follows:

In [59]:
car_cols = carfeatures.columns

print(car_cols)
print()
print(type(car_cols))

Index(['mpg', 'cylinders', 'displacement', 'horsepower', 'weight',
       'acceleration', 'vehicle_id'],
      dtype='str')

<class 'pandas.Index'>

<font size = "4">

- `.columns` is an *attribute*. It is a variable that "belongs" to an object.

- We manually assigned this attribute to a new variable called `car_cols`.

- It is a "Pandas Index" object.

- A Pandas Index also has attributes of its own:

In [60]:
car_colnames = car_cols.values

print(car_colnames)

# Is this a list? A Numpy array? Are you checking what objects are, or just coding with reckless abandon?

<StringArray>
[         'mpg',    'cylinders', 'displacement',   'horsepower',
       'weight', 'acceleration',   'vehicle_id']
Length: 7, dtype: str

<font size = "4">

- We could have extracted the names in a single line by "chaining"

In [61]:
car_colnames = carfeatures.columns.values
print(car_colnames)

print(type(car_colnames))
print(type(car_colnames[0]))

<StringArray>
[         'mpg',    'cylinders', 'displacement',   'horsepower',
       'weight', 'acceleration',   'vehicle_id']
Length: 7, dtype: str
<class 'pandas.arrays.StringArray'>
<class 'str'>

In [62]:

# manually..
mpg = carfeatures["mpg"]

# using car_colnames
mpg_alt = carfeatures[car_colnames[0]]
print(mpg)
print(mpg_alt)

0      18.0
1      15.0
2      18.0
3      16.0
4      17.0
       ...
393    27.0
394    44.0
395    32.0
396    28.0
397    31.0
Name: mpg, Length: 398, dtype: float64
0      18.0
1      15.0
2      18.0
3      16.0
4      17.0
       ...
393    27.0
394    44.0
395    32.0
396    28.0
397    31.0
Name: mpg, Length: 398, dtype: float64

In [63]:
# Did you check the TYPE ?!
print(type(mpg))

<class 'pandas.Series'>

<font size = "4">

- A single column of a "Pandas DataFrame" is a "Pandas Series".

- A Pandas Series is a set of 1-dimensional data. Similar to a NumPy array.

- We can also grab multiple columns from a DataFrame:

In [64]:
list_subsetcols = ["weight","mpg"]
subcols_carfeatures = carfeatures[list_subsetcols]

print(type(subcols_carfeatures))
print()
print(subcols_carfeatures)

<class 'pandas.DataFrame'>

     weight   mpg
0      3504  18.0
1      3693  15.0
2      3436  18.0
3      3433  16.0
4      3449  17.0
..      ...   ...
393    2790  27.0
394    2130  44.0
395    2295  32.0
396    2625  28.0
397    2720  31.0

[398 rows x 2 columns]

In [65]:
# list_subsetcols = ["weight","mpg"] # we created a variable list_subsetcols...
# subcols_carfeatures = carfeatures[list_subsetcols] # ...just to place it within the brackets

# skip the intermediate variable
subcols_carfeatures = carfeatures[["weight", "mpg"]]
print(subcols_carfeatures)

     weight   mpg
0      3504  18.0
1      3693  15.0
2      3436  18.0
3      3433  16.0
4      3449  17.0
..      ...   ...
393    2790  27.0
394    2130  44.0
395    2295  32.0
396    2625  28.0
397    2720  31.0

[398 rows x 2 columns]

In [66]:
print(car_colnames[4])
print(car_colnames[0])

weight
mpg

In [67]:
# Use car_colnames plus the indices 4, 0
list_subsetcols = [car_colnames[4], car_colnames[0]]
subcols_carfeatures = carfeatures[list_subsetcols]
print(subcols_carfeatures)

     weight   mpg
0      3504  18.0
1      3693  15.0
2      3436  18.0
3      3433  16.0
4      3449  17.0
..      ...   ...
393    2790  27.0
394    2130  44.0
395    2295  32.0
396    2625  28.0
397    2720  31.0

[398 rows x 2 columns]

<font size = "4">

**Exercise (car_features)**: Extract the `displacement`, `horsepower`, and `weight` variables as `altsub_carfeatures` using indices of `car_colnames` and print it.

In [68]:
# your answer here

altsub_carfeature = [car_colnames[2], car_colnames[3], car_colnames[4]]
print(carfeatures[altsub_carfeature])

     displacement horsepower  weight
0             307        130    3504
1             350        165    3693
2             318        150    3436
3             304        150    3433
4             302        140    3449
..            ...        ...     ...
393           140         86    2790
394            97         52    2130
395           135         84    2295
396           120         79    2625
397           119         82    2720

[398 rows x 3 columns]

<font size = "4">

**Exercise (coffee):** Extract the column names of `coffee` as `coffee_colnames`. How many columns are there?

In [69]:
# your answer here

coffee_colnames = coffee.columns.values

print(len(coffee_colnames))

26

<font size = "4">


**Exercise (carlsen):** Extract the `opponent_name` column. What is its type?

In [70]:
# your answer here
print(type(carlsen["opponent_name"]))

<class 'pandas.Series'>

<font size = "4">

**Exercise (netflix):** Extract the `title`, `type`, and `release_year` columns from `netflix`.

In [71]:
# your answer here
title = netflix["title"]
Type = netflix["type"]
release_year = netflix["release_year"]

<font size = "4">


**Exercise (social):** Create `social_colnames`, then use it with indices (rather than typing out column names) to extract the `Age` and `Primary_Platform` columns.

In [72]:
# your answer here
social_colnames = social.columns.values

## <span style="color:red"> III. Sort by column/variable </span>

<font size = "4">

- We can sort DataFrames according to one of the variables (i.e. one of the columns)

In [73]:
help(carfeatures.sort_values)

Help on method sort_values in module pandas.core.frame:

sort_values(
    by: IndexLabel,
    *,
    axis: Axis = 0,
    ascending: bool | list[bool] | tuple[bool, ...] = True,
    inplace: bool = False,
    kind: SortKind = 'quicksort',
    na_position: str = 'last',
    ignore_index: bool = False,
    key: ValueKeyFunc | None = None
) -> DataFrame | None method of pandas.DataFrame instance
    Sort by the values along either axis.

    Parameters
    ----------
    by : str or list of str
        Name or list of names to sort by.

        - if `axis` is 0 or `'index'` then `by` may contain index
          levels and/or column labels.
        - if `axis` is 1 or `'columns'` then `by` may contain column
          levels and/or index labels.
    axis : "{0 or 'index', 1 or 'columns'}", default 0
         Axis to be sorted.
    ascending : bool or list of bool, default True
         Sort ascending vs. descending. Specify list for multiple sort
         orders.  If this is a list of bools, must match the length of
         the by.
    inplace : bool, default False
         If True, perform operation in-place.
    kind : {'quicksort', 'mergesort', 'heapsort', 'stable'}, default 'quicksort'
         Choice of sorting algorithm. See also :func:`numpy.sort` for more
         information. `mergesort` and `stable` are the only stable algorithms. For
         DataFrames, this option is only applied when sorting on a single
         column or label.
    na_position : {'first', 'last'}, default 'last'
         Puts NaNs at the beginning if `first`; `last` puts NaNs at the
         end.
    ignore_index : bool, default False
         If True, the resulting axis will be labeled 0, 1, …, n - 1.
    key : callable, optional
        Apply the key function to the values
        before sorting. This is similar to the `key` argument in the
        builtin :meth:`sorted` function, with the notable difference that
        this `key` function should be *vectorized*. It should expect a
        ``Series`` and return a Series with the same shape as the input.
        It will be applied to each column in `by` independently. The values in the
        returned Series will be used as the keys for sorting.

    Returns
    -------
    DataFrame or None
        DataFrame with sorted values or None if ``inplace=True``.

    See Also
    --------
    DataFrame.sort_index : Sort a DataFrame by the index.
    Series.sort_values : Similar method for a Series.

    Examples
    --------
    >>> df = pd.DataFrame(
    ...     {
    ...         "col1": ["A", "A", "B", np.nan, "D", "C"],
    ...         "col2": [2, 1, 9, 8, 7, 4],
    ...         "col3": [0, 1, 9, 4, 2, 3],
    ...         "col4": ["a", "B", "c", "D", "e", "F"],
    ...     }
    ... )
    >>> df
      col1  col2  col3 col4
    0    A     2     0    a
    1    A     1     1    B
    2    B     9     9    c
    3  NaN     8     4    D
    4    D     7     2    e
    5    C     4     3    F

    **Sort by a single column**

    In this case, we are sorting the rows according to values in ``col1``:

    >>> df.sort_values(by=["col1"])
      col1  col2  col3 col4
    0    A     2     0    a
    1    A     1     1    B
    2    B     9     9    c
    5    C     4     3    F
    4    D     7     2    e
    3  NaN     8     4    D

    **Sort by multiple columns**

    You can also provide multiple columns to ``by`` argument, as shown below.
    In this example, the rows are first sorted according to ``col1``, and then
    the rows that have an identical value in ``col1`` are sorted according
    to ``col2``.

    >>> df.sort_values(by=["col1", "col2"])
      col1  col2  col3 col4
    1    A     1     1    B
    0    A     2     0    a
    2    B     9     9    c
    5    C     4     3    F
    4    D     7     2    e
    3  NaN     8     4    D

    **Sort in a descending order**

    The sort order can be reversed using ``ascending`` argument, as shown below:

    >>> df.sort_values(by="col1", ascending=False)
      col1  col2  col3 col4
    4    D     7     2    e
    5    C     4     3    F
    2    B     9     9    c
    0    A     2     0    a
    1    A     1     1    B
    3  NaN     8     4    D

    **Placing any** ``NA`` **first**

    Note that in the above example, the rows that contain an ``NA`` value in their
    ``col1`` are placed at the end of the dataframe. This behavior can be modified
    via ``na_position`` argument, as shown below:

    >>> df.sort_values(by="col1", ascending=False, na_position="first")
      col1  col2  col3 col4
    3  NaN     8     4    D
    4    D     7     2    e
    5    C     4     3    F
    2    B     9     9    c
    0    A     2     0    a
    1    A     1     1    B

    **Customized sort order**

    The ``key`` argument allows for a further customization of sorting behaviour.
    For example, you may want
    to ignore the `letter's case <https://en.wikipedia.org/wiki/Letter_case>`__
    when sorting strings:

    >>> df.sort_values(by="col4", key=lambda col: col.str.lower())
       col1  col2  col3 col4
    0    A     2     0    a
    1    A     1     1    B
    2    B     9     9    c
    3  NaN     8     4    D
    4    D     7     2    e
    5    C     4     3    F

    Another typical example is
    `natural sorting <https://en.wikipedia.org/wiki/Natural_sort_order>`__.
    This can be done using
    ``natsort`` `package <https://github.com/SethMMorton/natsort>`__,
    which provides a function to generate a key
    to sort data in their natural order:

    >>> df = pd.DataFrame(
    ...     {
    ...         "hours": ["0hr", "128hr", "0hr", "64hr", "64hr", "128hr"],
    ...         "mins": [
    ...             "10mins",
    ...             "40mins",
    ...             "40mins",
    ...             "40mins",
    ...             "10mins",
    ...             "10mins",
    ...         ],
    ...         "value": [10, 20, 30, 40, 50, 60],
    ...     }
    ... )
    >>> df
       hours    mins  value
    0    0hr  10mins     10
    1  128hr  40mins     20
    2    0hr  40mins     30
    3   64hr  40mins     40
    4   64hr  10mins     50
    5  128hr  10mins     60
    >>> from natsort import natsort_keygen
    >>> df.sort_values(
    ...     by=["hours", "mins"],
    ...     key=natsort_keygen(),
    ... )
       hours    mins  value
    0    0hr  10mins     10
    2    0hr  40mins     30
    4   64hr  10mins     50
    3   64hr  40mins     40
    5  128hr  10mins     60
    1  128hr  40mins     20

In [74]:
# sort the data-set by one of the variables
carsorted = carfeatures.sort_values(by = "mpg")
print(carsorted)

      mpg  cylinders  displacement horsepower  weight  acceleration vehicle_id
28    9.0          8           304        193    4732          18.5  H-1690088
25   10.0          8           360        215    4615          14.0  F-1690055
26   10.0          8           307        200    4376          15.0  C-1690066
67   11.0          8           429        208    4633          11.0  M-1690517
27   11.0          8           318        210    4382          13.5  D-1690077
..    ...        ...           ...        ...     ...           ...        ...
326  43.4          4            90         48    2335          23.7  V-1693366
394  44.0          4            97         52    2130          24.6  V-1694114
325  44.3          4            90         48    2085          21.7  V-1693355
329  44.6          4            91         67    1850          13.8  H-1693399
322  46.6          4            86         65    2110          17.9  M-1693322

[398 rows x 7 columns]

In [75]:
# above we went from lowest mileage to highest mileage (ascending order)
# 
# To reverse the order, pass in the argument ascending = False 

carsorted = carfeatures.sort_values(by = "mpg", ascending = False)
print(carsorted)

      mpg  cylinders  displacement horsepower  weight  acceleration vehicle_id
322  46.6          4            86         65    2110          17.9  M-1693322
329  44.6          4            91         67    1850          13.8  H-1693399
325  44.3          4            90         48    2085          21.7  V-1693355
394  44.0          4            97         52    2130          24.6  V-1694114
326  43.4          4            90         48    2335          23.7  V-1693366
..    ...        ...           ...        ...     ...           ...        ...
67   11.0          8           429        208    4633          11.0  M-1690517
27   11.0          8           318        210    4382          13.5  D-1690077
25   10.0          8           360        215    4615          14.0  F-1690055
26   10.0          8           307        200    4376          15.0  C-1690066
28    9.0          8           304        193    4732          18.5  H-1690088

[398 rows x 7 columns]

<font size = "4">

**Exercise (coffee):** Sort by `dwell_time_minutes` from highest to lowest and display it.

In [76]:
# your answer here

coffeesort = coffee.sort_values(by = "dwell_time_minutes", ascending = False)
print(coffeesort)

         store_transaction_id   coffee_brand      city_location  \
312         ID_COF_948925DFA5    Fore Coffee            Bandung
11022  ID_COF_26Q4_23B93B2FBE    Fore Coffee      Jakarta Pusat
10545  ID_COF_26Q4_277FB4F735  Tomoro Coffee             Bekasi
2003        ID_COF_070B63A071    Fore Coffee              Depok
5963        ID_COF_1B397DAEFB   Point Coffee    Jakarta Selatan
...                       ...            ...                ...
5528        ID_COF_278F704CD6  Kopi Kenangan    Jakarta Selatan
9348        ID_COF_577779E5A9   Point Coffee  Tangerang Selatan
9345        ID_COF_512916490F   Point Coffee  Tangerang Selatan
2754        ID_COF_0871545544  Kopi Kenangan      Jakarta Barat
9394        ID_COF_BAAEB11686   Point Coffee  Tangerang Selatan

                      store_format  competitor_density_500m  base_price_idr  \
312    Standalone Shophouse / Ruko                        1           32000
11022                   Mall Kiosk                        9           25000
10545  Standalone Shophouse / Ruko                        4           15000
2003                    Mall Kiosk                        2           23000
5963   Standalone Shophouse / Ruko                       11           18000
...                            ...                      ...             ...
5528            Office Tower Lobby                       10           26000
9348   Standalone Shophouse / Ruko                        5           22000
9345   Standalone Shophouse / Ruko                        2           18000
2754                    Mall Kiosk                       10           22000
9394   Standalone Shophouse / Ruko                        4           17000

       discount_voucher_pct          order_method  daily_cups_sold  \
312                    37.0   Dine-In POS Cashier              272
11022                  13.1   Dine-In POS Cashier              560
10545                  18.4   Dine-In POS Cashier              869
2003                   13.2   Dine-In POS Cashier              325
5963                   26.4   Dine-In POS Cashier              461
...                     ...                   ...              ...
5528                    7.7     Mobile App Pickup              550
9348                   27.1  Online Ojol Delivery              354
9345                   22.0     Mobile App Pickup              482
2754                   17.7  Online Ojol Delivery              828
9394                    1.1  Online Ojol Delivery              357

       customer_review_rating  ... revenue_per_competitor_density  \
312                       4.5  ...                      2741760.0
11022                     4.0  ...                      1216600.0
10545                     5.0  ...                      2127312.0
2003                      5.0  ...                      2162767.0
5963                      3.5  ...                       508944.0
...                       ...  ...                            ...
5528                      4.0  ...                      1199900.0
9348                      5.0  ...                       946242.0
9345                      4.5  ...                      2255760.0
2754                      4.5  ...                      1362888.0
9394                      5.0  ...                      1200448.0

      price_competitiveness_ratio dwell_time_to_spend_ratio  \
312                         1.006                     11.90
11022                       1.022                     11.05
10545                       0.600                     19.61
2003                        1.000                     12.02
5963                        0.666                     18.12
...                           ...                       ...
5528                        1.206                      0.21
9348                        0.814                      0.31
9345                        0.713                      0.36
2754                        0.903                      0.28
9394                        0.853                      0.30

       cannibalization_risk_index  customer_price_sensitivity_score  \
312                          4.14                              6.48
11022                        5.65                              4.82
10545                        4.36                              6.73
2003                         3.25                              5.12
5963                         7.11                              7.03
...                           ...                               ...
5528                         5.56                              1.82
9348                         5.08                              4.30
9345                         3.83                              4.34
2754                         6.19                              5.70
9394                         3.62                              4.65

       outlet_operating_margin_estimate_pct  customer_brand_loyalty_tier  \
312                                    25.0     Promo-Chaser-Opportunist
11022                                  27.4       At-Risk-Churn-Switcher
10545                                  35.6      Value-Conscious-Regular
2003                                   27.4            Die-Hard-Loyalist
5963                                   32.8       At-Risk-Churn-Switcher
...                                     ...                          ...
5528                                   35.3       At-Risk-Churn-Switcher
9348                                   32.5      Value-Conscious-Regular
9345                                   34.3      Value-Conscious-Regular
2754                                   25.8       At-Risk-Churn-Switcher
9394                                   41.6            Die-Hard-Loyalist

         primary_brand_switch_driver  \
312       Cheaper-Competitor-Opening
11022       Taste-Inconsistency-Drop
10545        Long-Queue-Pickup-Delay
2003   Voucher-Exhaustion-Price-Hike
5963        Taste-Inconsistency-Drop
...                              ...
5528        Taste-Inconsistency-Drop
9348      Cheaper-Competitor-Opening
9345            Lack-Of-Seating-WiFi
2754         Long-Queue-Pickup-Delay
9394   Voucher-Exhaustion-Price-Hike

                           cot_retail_dynamics_rationale  confidence_score
312    Gerai/transaksi 'ID_COF_948925DFA5' dari jarin...             0.990
11022  Gerai/transaksi 'ID_COF_26Q4_23B93B2FBE' dari ...             0.983
10545  Gerai/transaksi 'ID_COF_26Q4_277FB4F735' dari ...             0.982
2003   Gerai/transaksi 'ID_COF_070B63A071' dari jarin...             0.953
5963   Gerai/transaksi 'ID_COF_1B397DAEFB' dari jarin...             0.982
...                                                  ...               ...
5528   Gerai/transaksi 'ID_COF_278F704CD6' dari jarin...             0.963
9348   Gerai/transaksi 'ID_COF_577779E5A9' dari jarin...             0.988
9345   Gerai/transaksi 'ID_COF_512916490F' dari jarin...             0.989
2754   Gerai/transaksi 'ID_COF_0871545544' dari jarin...             0.952
9394   Gerai/transaksi 'ID_COF_BAAEB11686' dari jarin...             0.990

[13000 rows x 26 columns]

<font size = "4">

**Exercise (carlsen):** Sort by `opponent_rating` from lowest to highest and display it.

In [77]:
# your answer here

<font size = "4">


**Exercise (netflix):** Sort by `release_year` AND `duration` so the newest and longest titles coming first, then display it.

In [78]:
# your answer here
netflixsort = netflix.sort_values(by = ["release_year", "duration"])
print(netflixsort)

     show_id     type                                          title  \
4250   s4251  TV Show              Pioneers: First Women Filmmakers*
8205   s8206    Movie                           The Battle of Midway
7790   s7791    Movie                                 Prelude to War
8763   s8764    Movie                WWII: Report from the Aleutians
8660   s8661    Movie  Undercover: How to Operate Behind Enemy Lines
...      ...      ...                                            ...
781     s782    Movie          Black Holes | The Edge of All We Know
877     s878    Movie                                   Cinema Bandi
894     s895    Movie                         Dance of the Forty One
910     s911    Movie                                        Monster
1329   s1330    Movie          The Misadventures of Hedi and Cokeman

                director                                               cast  \
4250                 NaN                                                NaN
8205           John Ford                          Henry Fonda, Jane Darwell
7790         Frank Capra                                                NaN
8763         John Huston                                                NaN
8660           John Ford                                                NaN
...                  ...                                                ...
781        Peter Galison                                                NaN
877   Praveen Kandregula  Vikas Vasistha, Sandeep Varanasi, Rag Mayur, T...
894         David Pablos  Alfonso Herrera, Emiliano Zurita, Mabel Cadena...
910      Anthony Mandler  Kelvin Harrison Jr., Jennifer Hudson, Jeffrey ...
1329        Julien Royal  Hedi Bouchenafa, Nassim Lyes, Fred Testot, Jul...

             country         date_added  release_year rating  duration  \
4250             NaN  December 30, 2018          1925  TV-14  1 Season
8205   United States     March 31, 2017          1942  TV-14    18 min
7790   United States     March 31, 2017          1942  TV-14    52 min
8763   United States     March 31, 2017          1943  TV-PG    45 min
8660   United States     March 31, 2017          1943  TV-PG    61 min
...              ...                ...           ...    ...       ...
781              NaN       June 2, 2021          2021  TV-14    99 min
877            India       May 14, 2021          2021  TV-MA    99 min
894   Mexico, Brazil       May 12, 2021          2021  TV-MA    99 min
910    United States        May 7, 2021          2021  TV-MA    99 min
1329          France  February 10, 2021          2021  TV-MA    99 min

                                              listed_in  \
4250                                           TV Shows
8205                      Classic Movies, Documentaries
7790                      Classic Movies, Documentaries
8763                                      Documentaries
8660                      Classic Movies, Documentaries
...                                                 ...
781                                       Documentaries
877   Comedies, Independent Movies, International Mo...
894    Dramas, Independent Movies, International Movies
910                                              Dramas
1329                     Comedies, International Movies

                                            description
4250  This collection restores films from women who ...
8205  Director John Ford captures combat footage of ...
7790  Frank Capra's documentary chronicles the rise ...
8763  Filmmaker John Huston narrates this Oscar-nomi...
8660  This World War II-era training film dramatizes...
...                                                 ...
781   Follow scientists on their quest to understand...
877   A struggling rickshaw driver’s life takes a ro...
894   A gay congressman marries the Mexican presiden...
910   A talented teen implicated in a robbery-turned...
1329  In Paris, two dysfunctional dealers use family...

[8807 rows x 12 columns]

<font size = "4">


**Exercise (social):** Sort by `Daily_Usage_Hours` from highest to lowest and display it.

In [79]:
# your answer here

## <span style="color:red"> IV. Subsetting by row/column position </span>

<font size = "4">

- Use the `.loc` attribute to grab the value of a variable from a given row.

- In addition, each DataFrame has an "iloc" attribute. This stands for "integer-location based indexing".

- **Important Note:** `.iloc` is an attribute, not a method! You use square brackets `[]` not parentheses!

In [80]:
print(carfeatures)

      mpg  cylinders  displacement horsepower  weight  acceleration vehicle_id
0    18.0          8           307        130    3504          12.0  C-1689780
1    15.0          8           350        165    3693          11.5  B-1689791
2    18.0          8           318        150    3436          11.0  P-1689802
3    16.0          8           304        150    3433          12.0  A-1689813
4    17.0          8           302        140    3449          10.5  F-1689824
..    ...        ...           ...        ...     ...           ...        ...
393  27.0          4           140         86    2790          15.6  F-1694103
394  44.0          4            97         52    2130          24.6  V-1694114
395  32.0          4           135         84    2295          11.6  D-1694125
396  28.0          4           120         79    2625          18.6  F-1694136
397  31.0          4           119         82    2720          19.4  C-1694147

[398 rows x 7 columns]

In [81]:
car0 = carfeatures.loc[0]

print(car0)

mpg                  18.0
cylinders               8
displacement          307
horsepower            130
weight               3504
acceleration         12.0
vehicle_id      C-1689780
Name: 0, dtype: object

In [82]:
# Above, see that car 0 has 18.0 mpg
# The value "18.0" is in the first row, and corresponds to the first column
# (the index column on the left is NOT considered a column/variable)

car0_mpg =carfeatures.loc[0, "mpg"]
print(car0_mpg)

18.0

In [83]:

# Since Python starts counting from zero, this is in row 0 column 0

car0_mpg = carfeatures.iloc[0,0]
print(car0_mpg)

18.0

In [84]:
# Above, see that car 3 has weight of 3433
# Counting from zero, the value "3433" is in
# row 3, column
# The value "3433" is in row 3, column 4

car3_weight = carfeatures.iloc[3, 4]
print(car3_weight)

3433

In [85]:
# Grabbing multiple rows

car1_6 = carfeatures.loc[1:6]

print(car1_6)

    mpg  cylinders  displacement horsepower  weight  acceleration vehicle_id
1  15.0          8           350        165    3693          11.5  B-1689791
2  18.0          8           318        150    3436          11.0  P-1689802
3  16.0          8           304        150    3433          12.0  A-1689813
4  17.0          8           302        140    3449          10.5  F-1689824
5  15.0          8           429        198    4341          10.0  F-1689835
6  14.0          8           454        220    4354           9.0  C-1689846

In [86]:
# multiple rows of a single column

car1_6horse = carfeatures.loc[1:6, "horsepower"]

print(car1_6horse)

1    165
2    150
3    150
4    140
5    198
6    220
Name: horsepower, dtype: str

In [87]:
# Let's grab ALL the features for car 0 (mpg, cylinders, displacement, ..., vehicle_id)

# So we want all the entries along row zero. 
# Use a ":" (colon) for the column index to grab ALL the columns

car0_features = carfeatures.iloc[0,:]
print(car0_features)
print()
print(type(car0_features))

mpg                  18.0
cylinders               8
displacement          307
horsepower            130
weight               3504
acceleration         12.0
vehicle_id      C-1689780
Name: 0, dtype: object

<class 'pandas.Series'>

In [88]:
# Grab all columns of car 3
car3_features = carfeatures.iloc[3,:]
print(car3_features)

mpg                  16.0
cylinders               8
displacement          304
horsepower            150
weight               3433
acceleration         12.0
vehicle_id      A-1689813
Name: 3, dtype: object

In [89]:
print(carfeatures)

      mpg  cylinders  displacement horsepower  weight  acceleration vehicle_id
0    18.0          8           307        130    3504          12.0  C-1689780
1    15.0          8           350        165    3693          11.5  B-1689791
2    18.0          8           318        150    3436          11.0  P-1689802
3    16.0          8           304        150    3433          12.0  A-1689813
4    17.0          8           302        140    3449          10.5  F-1689824
..    ...        ...           ...        ...     ...           ...        ...
393  27.0          4           140         86    2790          15.6  F-1694103
394  44.0          4            97         52    2130          24.6  V-1694114
395  32.0          4           135         84    2295          11.6  D-1694125
396  28.0          4           120         79    2625          18.6  F-1694136
397  31.0          4           119         82    2720          19.4  C-1694147

[398 rows x 7 columns]

In [90]:
# Column 0 corresponds to "mpg" (the index column on the far left doesn't count)

# Grab the entire column 0, which means grabbing ALL the rows

car_mpg = carfeatures.iloc[:, 0]
print(car_mpg)

0      18.0
1      15.0
2      18.0
3      16.0
4      17.0
       ...
393    27.0
394    44.0
395    32.0
396    28.0
397    31.0
Name: mpg, Length: 398, dtype: float64

In [91]:
# horsepower is column 3
# grab ALL rows of column 3

car_horsepower = carfeatures.iloc[:, 3]
car_horsepower

0      130
1      165
2      150
3      150
4      140
      ...
393     86
394     52
395     84
396     79
397     82
Name: horsepower, Length: 398, dtype: str

In [92]:
# Grab all features for cars 0, 4, 396 (so rows 0, 4, 396)

cargroup_features = carfeatures.iloc[[0, 4, 396],:]
print(cargroup_features)
print(type(cargroup_features))

      mpg  cylinders  displacement horsepower  weight  acceleration vehicle_id
0    18.0          8           307        130    3504          12.0  C-1689780
4    17.0          8           302        140    3449          10.5  F-1689824
396  28.0          4           120         79    2625          18.6  F-1694136
<class 'pandas.DataFrame'>

In [93]:
# Grab all features for cars 0, 4, 396 (so rows 0, 4, 396)

group_rows = [0, 4, 396]
cargroup_features = carfeatures.iloc[ group_rows, : ]
print(cargroup_features)

      mpg  cylinders  displacement horsepower  weight  acceleration vehicle_id
0    18.0          8           307        130    3504          12.0  C-1689780
4    17.0          8           302        140    3449          10.5  F-1689824
396  28.0          4           120         79    2625          18.6  F-1694136

In [94]:
# Grab mpg, weight, vehicle_id for ALL cars (columns 0, 4, 6)

subfeatures = carfeatures.iloc[ : , [0, 4, 6] ]
print(subfeatures)

      mpg  weight vehicle_id
0    18.0    3504  C-1689780
1    15.0    3693  B-1689791
2    18.0    3436  P-1689802
3    16.0    3433  A-1689813
4    17.0    3449  F-1689824
..    ...     ...        ...
393  27.0    2790  F-1694103
394  44.0    2130  V-1694114
395  32.0    2295  D-1694125
396  28.0    2625  F-1694136
397  31.0    2720  C-1694147

[398 rows x 3 columns]

In [95]:
# Grab mpg, weight, vehicle_id for ALL cars (columns 0, 4, 6)

sub_cols = [0, 4, 6]
subfeatures = carfeatures.iloc[ : , sub_cols]
print(subfeatures)

      mpg  weight vehicle_id
0    18.0    3504  C-1689780
1    15.0    3693  B-1689791
2    18.0    3436  P-1689802
3    16.0    3433  A-1689813
4    17.0    3449  F-1689824
..    ...     ...        ...
393  27.0    2790  F-1694103
394  44.0    2130  V-1694114
395  32.0    2295  D-1694125
396  28.0    2625  F-1694136
397  31.0    2720  C-1694147

[398 rows x 3 columns]

In [96]:
# Grab mpg, weight, vehicle_id for cars 0, 4, 396
# So we need rows 0, 4, 396
# and columns 0, 4, 6

subdata = carfeatures.iloc[ [0, 4, 396], [0, 4, 6] ]
print(subdata)

      mpg  weight vehicle_id
0    18.0    3504  C-1689780
4    17.0    3449  F-1689824
396  28.0    2625  F-1694136

### Subsetting blocks of rows

In [97]:
# let's grab all features for the first 5 cars
# (rows 0, 1, 2, 3, 4)

first_5_cars = carfeatures.iloc[ :5, :]
print(first_5_cars)

    mpg  cylinders  displacement horsepower  weight  acceleration vehicle_id
0  18.0          8           307        130    3504          12.0  C-1689780
1  15.0          8           350        165    3693          11.5  B-1689791
2  18.0          8           318        150    3436          11.0  P-1689802
3  16.0          8           304        150    3433          12.0  A-1689813
4  17.0          8           302        140    3449          10.5  F-1689824

In [98]:
# let's grab all features for the first 5 cars
# (rows 0, 1, 2, 3, 4)

# we start with row 0
# the first row we *exclude* is row 5
first_5_cars = carfeatures.iloc[ 0:5, :]
print(first_5_cars)

    mpg  cylinders  displacement horsepower  weight  acceleration vehicle_id
0  18.0          8           307        130    3504          12.0  C-1689780
1  15.0          8           350        165    3693          11.5  B-1689791
2  18.0          8           318        150    3436          11.0  P-1689802
3  16.0          8           304        150    3433          12.0  A-1689813
4  17.0          8           302        140    3449          10.5  F-1689824

In [99]:
# if we shift the indices by 1
# (change 0:5 --> 1:6)
# Then we will grab rows (1,2,3,4,5)

cars_1_thru_5 = carfeatures.iloc[ 1:6, :]

# we start with row 1
# the first row we *exclude* is row 6

print(cars_1_thru_5)

    mpg  cylinders  displacement horsepower  weight  acceleration vehicle_id
1  15.0          8           350        165    3693          11.5  B-1689791
2  18.0          8           318        150    3436          11.0  P-1689802
3  16.0          8           304        150    3433          12.0  A-1689813
4  17.0          8           302        140    3449          10.5  F-1689824
5  15.0          8           429        198    4341          10.0  F-1689835

In [100]:
# grab rows 211-219 (so 220 is the first one we exclude)
carfeatures.iloc[ 211:220 , :]

      mpg  cylinders  displacement horsepower  weight  acceleration vehicle_id
211  16.5          6           168        120    3820          16.7  M-1692101
212  16.5          8           350        180    4380          12.1  C-1692112
213  13.0          8           350        145    4055          12.0  C-1692123
214  13.0          8           302        130    3870          15.0  F-1692134
215  13.0          8           318        150    3755          14.0  D-1692145
216  31.5          4            98         68    2045          18.5  H-1692156
217  30.0          4           111         80    2155          14.8  B-1692167
218  36.0          4            79         58    1825          18.6  R-1692178
219  25.5          4           122         96    2300          15.5  P-1692189

In [101]:
print(carfeatures)

      mpg  cylinders  displacement horsepower  weight  acceleration vehicle_id
0    18.0          8           307        130    3504          12.0  C-1689780
1    15.0          8           350        165    3693          11.5  B-1689791
2    18.0          8           318        150    3436          11.0  P-1689802
3    16.0          8           304        150    3433          12.0  A-1689813
4    17.0          8           302        140    3449          10.5  F-1689824
..    ...        ...           ...        ...     ...           ...        ...
393  27.0          4           140         86    2790          15.6  F-1694103
394  44.0          4            97         52    2130          24.6  V-1694114
395  32.0          4           135         84    2295          11.6  D-1694125
396  28.0          4           120         79    2625          18.6  F-1694136
397  31.0          4           119         82    2720          19.4  C-1694147

[398 rows x 7 columns]

In [102]:
# grab last 3 rows (rows 395, 396, and 397)
carfeatures.iloc[ -3: , :]

      mpg  cylinders  displacement horsepower  weight  acceleration vehicle_id
395  32.0          4           135         84    2295          11.6  D-1694125
396  28.0          4           120         79    2625          18.6  F-1694136
397  31.0          4           119         82    2720          19.4  C-1694147

In [103]:
# grab 3rd from last row and 2nd from last row (exclude last row)
carfeatures.iloc[ -3:-1 , :]

      mpg  cylinders  displacement horsepower  weight  acceleration vehicle_id
395  32.0          4           135         84    2295          11.6  D-1694125
396  28.0          4           120         79    2625          18.6  F-1694136

<font size = "4">

Works similarly for blocks of columns, or blocks of both rows and columns

**Exercise:** Extract the columns corresponding to displacement, horsepower, and weight for all cars using ``.iloc``. The column indices should be of the form ``start:stop`` for appropriate integers ``start`` and ``stop``

**Exercise:** Extract the weight, acceleration, and vehicle_id information for cars 28, 29, 30, 31, 32 using ":" for both row and column indices

In [129]:
## your answer here

subfeatures = carfeatures.iloc[ 28:33 , 2:5 ]
print(subfeatures)

    displacement horsepower  weight
28           304        193    4732
29            97         88    2130
30           140         90    2264
31           113         95    2228
32            98        NaN    2046

<font size = "4">

**Exercise:** Create a dataset ``car_ascendingweight`` which sorts the cars from lowest to highest weight. Then extract the subset of the data corresponding to the 5 cars with the lowest weight (all their features, not just their weight)

In [131]:
# your answer here

car_ascendingweight = carfeatures.sort_values(by = "weight")

print(car_ascendingweight.iloc[ :6])

      mpg  cylinders  displacement horsepower  weight  acceleration vehicle_id
54   35.0          4            72         69    1613          18.0  D-1690374
144  31.0          4            76         52    1649          16.5  T-1691364
343  39.1          4            79         58    1755          16.9  T-1693553
345  35.1          4            81         60    1760          16.1  H-1693575
53   31.0          4            71         65    1773          19.0  T-1690363
181  33.0          4            91         53    1795          17.5  H-1691771

<font size = "4">


**Exercise (coffee):** Use `.loc` to grab the `coffee_brand` value for row 0.

In [106]:
# your answer here

<font size = "4">

**Exercise (carlsen):** Use `.iloc` to extract the last 5 games (all columns).

In [107]:
# your answer here

<font size = "4">

**Exercise (netflix):** Use `.iloc` with `start:stop` indices to extract rows 100 through 109 and the first 3 columns.

In [108]:
# your answer here

<font size = "4">


**Exercise (social):** Sort `social` from highest to lowest `Academic_Performance_GPA`, then use `.loc` to extract the 10 students with the highest GPA.

In [109]:
# your answer here

## <span style="color:red"> V. Adding Variables </span>

<font size = "4">

- Sometimes we don't want to simply read in a dataset, but **manipulate** the data in some way
- One of the most simple data manipulations is to add new variables/columns

We'll demonstrate with a data-set of the heights and weights of a sample of people. The dataset is from the Statistics Online Computational Resource (SOCR)

In [110]:
df_ht_wt = pd.read_csv("data_raw/SOCR-HeightWeight.csv")
print(df_ht_wt.columns.values)
print()
print(df_ht_wt)

<StringArray>
['Height(Inches)', 'Weight(Pounds)']
Length: 2, dtype: str

       Height(Inches)  Weight(Pounds)
0            65.78331        112.9925
1            71.51521        136.4873
2            69.39874        153.0269
3            68.21660        142.3354
4            67.78781        144.2971
...               ...             ...
24995        69.50215        118.0312
24996        64.54826        120.1932
24997        64.69855        118.2655
24998        67.52918        132.2682
24999        68.87761        124.8742

[25000 rows x 2 columns]

<font size = "4">

- The dataset contains the height and weight of people measured in inches and pounds, respectively. 
- Using these two variables, we can calculate a new variable: the BMI (Body Mass Index) of each person.
- The formula for BMI is given by the formula:
$$\textrm{BMI } = \frac{\textrm{weight in kg}}{\left(\textrm{height in meters}\right)^2}$$

In [111]:
# Grab height and weight and convert to correct units

def pounds_to_kg(wt):
    return wt*0.45359237

def inches_to_meters(ht):
    ht_mm = ht*25.4
    return ht_mm*1e-3

ht_inch = df_ht_wt["Height(Inches)"]
wt_lbs = df_ht_wt["Weight(Pounds)"]

ht_meters = ht_inch.apply(inches_to_meters)
ht_meters.name = "Height(Meters)"
wt_kg = wt_lbs.apply(pounds_to_kg)
wt_kg.name = "Weight(Kilograms)"

<font size = "4">

**Exercise**: Repeat the operations in the last cell, but grab ``ht_inch`` and ``wt_lbs`` using ``.iloc`` instead of the column names

In [112]:
# your code here

<font size = "4">

Now, calculate BMI using these two variables and add to the dataset

In [113]:
df_ht_wt.head()

   Height(Inches)  Weight(Pounds)
0        65.78331        112.9925
1        71.51521        136.4873
2        69.39874        153.0269
3        68.21660        142.3354
4        67.78781        144.2971

In [114]:
# Math operations on Pandas series work very similarly to Numpy arrays

BMI = wt_kg/ht_meters**2

# assign the new Pandas series to a new column of the dataframe
df_ht_wt["BMI"] = BMI

In [115]:
df_ht_wt.head()

   Height(Inches)  Weight(Pounds)        BMI
0        65.78331        112.9925  18.357624
1        71.51521        136.4873  18.762630
2        69.39874        153.0269  22.338958
3        68.21660        142.3354  21.504586
4        67.78781        144.2971  22.077643

<font size = "4">

**Application:** Random Assignment

- Random assignment is an experimental technique for dividing a data set into groups using randomization
- Typically a data point has an equal probability of being placed in each group (but not necessary)
- Let's say we want to divide up the height/weight dataset into 4 groups. We can use Numpy.random to assign each person the number 1, 2, 3, or 4

In [116]:
import numpy as np

# get size of data-set
num_rows, num_cols = df_ht_wt.shape

# randomly generate a number (1,2,3, or 4) for each person in the dataset
group_no = np.random.choice([1, 2, 3, 4], size = num_rows)

df_ht_wt["GroupID"] = group_no

In [117]:
df_ht_wt.head()

   Height(Inches)  Weight(Pounds)        BMI  GroupID
0        65.78331        112.9925  18.357624        3
1        71.51521        136.4873  18.762630        1
2        69.39874        153.0269  22.338958        2
3        68.21660        142.3354  21.504586        4
4        67.78781        144.2971  22.077643        3

<font size = "4">

**Practice with new data**

**Exercise (coffee):** Write a function `idr_to_usd` (use 1 USD = 16,500 IDR). Use `.apply()` on `base_price_idr` to add a new column `base_price_usd`.

In [118]:
# your solution here

<font size = "4">


**Exercise (carlsen):** Add a column `rating_diff` equal to `player_rating` minus `opponent_rating`.

In [119]:
# your solution here

<font size = "4">

**Exercise (netflix):** Add a column `years_since_release` equal to 2026 minus `release_year`.

In [120]:
# your solution here

<font size = "4">

**Exercise (social):** Randomly assign each student to group `"A"` or `"B"` and store it in a new column `group`.

In [121]:
# your solution here

## <span style="color:red"> VI. Filtering Dataframes Based on Logical Expressions </span>

<font size = "4">

(i) Filtering using ```pandas.query()``` 

```python
data.query("logical expression")
```

In [122]:
high_mileagecars = carfeatures.query("mpg >= 25")
print(high_mileagecars)

      mpg  cylinders  displacement horsepower  weight  acceleration vehicle_id
18   27.0          4            97         88    2130          14.5  D-1689978
19   26.0          4            97         46    1835          20.5  V-1689989
20   25.0          4           110         87    2672          17.5  P-1690000
22   25.0          4           104         95    2375          17.5  S-1690022
23   26.0          4           121        113    2234          12.5  B-1690033
..    ...        ...           ...        ...     ...           ...        ...
393  27.0          4           140         86    2790          15.6  F-1694103
394  44.0          4            97         52    2130          24.6  V-1694114
395  32.0          4           135         84    2295          11.6  D-1694125
396  28.0          4           120         79    2625          18.6  F-1694136
397  31.0          4           119         82    2720          19.4  C-1694147

[169 rows x 7 columns]

In [123]:
group_4 = df_ht_wt.query("GroupID == 4")
print(group_4)

       Height(Inches)  Weight(Pounds)        BMI  GroupID
3            68.21660        142.3354  21.504586        4
8            67.90265        112.3723  17.135001        4
10           66.48769        127.4516  20.270344        4
16           66.46100        129.5023  20.613040        4
24           67.62804        141.8501  21.805917        4
...               ...             ...        ...      ...
24978        69.62400        141.5823  20.534746        4
24983        63.77967        111.4911  19.269656        4
24987        68.86794        142.8494  21.175932        4
24996        64.54826        120.1932  20.281923        4
24998        67.52918        132.2682  20.392515        4

[6262 rows x 4 columns]

In [124]:
# Use "and" / "or" for logical operations on queries

car_subset = carfeatures.query("(acceleration >= 12) and (acceleration < 18)")
print(car_subset)

      mpg  cylinders  displacement horsepower  weight  acceleration vehicle_id
0    18.0          8           307        130    3504          12.0  C-1689780
3    16.0          8           304        150    3433          12.0  A-1689813
14   24.0          4           113         95    2372          15.0  T-1689934
15   22.0          6           198         95    2833          15.5  P-1689945
16   18.0          6           199         97    2774          15.5  A-1689956
..    ...        ...           ...        ...     ...           ...        ...
389  22.0          6           232        112    2835          14.7  F-1694059
390  32.0          4           144         96    2665          13.9  T-1694070
391  36.0          4           135         84    2370          13.0  D-1694081
392  27.0          4           151         90    2950          17.3  C-1694092
393  27.0          4           140         86    2790          15.6  F-1694103

[290 rows x 7 columns]

<font size = "4">

(ii) Expressions with colnames + global variables (@)

In [125]:
# You can invoke global variables into the query by using @variablename
# If you don't include @, then Python will try to look for a column with 
# that name.

threshold = 25
high_mileagecars = carfeatures.query("mpg >= @threshold")
print(high_mileagecars)

      mpg  cylinders  displacement horsepower  weight  acceleration vehicle_id
18   27.0          4            97         88    2130          14.5  D-1689978
19   26.0          4            97         46    1835          20.5  V-1689989
20   25.0          4           110         87    2672          17.5  P-1690000
22   25.0          4           104         95    2375          17.5  S-1690022
23   26.0          4           121        113    2234          12.5  B-1690033
..    ...        ...           ...        ...     ...           ...        ...
393  27.0          4           140         86    2790          15.6  F-1694103
394  44.0          4            97         52    2130          24.6  V-1694114
395  32.0          4           135         84    2295          11.6  D-1694125
396  28.0          4           120         79    2625          18.6  F-1694136
397  31.0          4           119         82    2720          19.4  C-1694147

[169 rows x 7 columns]

In [126]:
lb = 12
ub = 18

car_subset = carfeatures.query("(acceleration >= @lb) and (acceleration < @ub)")
print(car_subset)

      mpg  cylinders  displacement horsepower  weight  acceleration vehicle_id
0    18.0          8           307        130    3504          12.0  C-1689780
3    16.0          8           304        150    3433          12.0  A-1689813
14   24.0          4           113         95    2372          15.0  T-1689934
15   22.0          6           198         95    2833          15.5  P-1689945
16   18.0          6           199         97    2774          15.5  A-1689956
..    ...        ...           ...        ...     ...           ...        ...
389  22.0          6           232        112    2835          14.7  F-1694059
390  32.0          4           144         96    2665          13.9  T-1694070
391  36.0          4           135         84    2370          13.0  D-1694081
392  27.0          4           151         90    2950          17.3  C-1694092
393  27.0          4           140         86    2790          15.6  F-1694103

[290 rows x 7 columns]

<font size = "4">

(iii) Handling white space

Ever wonder why I give folders names like "Lecture_11" instead of "Lecture 11"? Or name notebooks things like "Lecture9.ipynb" instead of "Lecture 9.ipynb"?

Because handling white spaces on a computer can be annoying in certain situations, as we will see here:

In [127]:
# same data set, but column/variable 0 is "miles per gallon" instead of "mpg"

new_dset = pd.read_csv("data_raw/subfolder1/annoying_subfolder/features-bad-spacing.csv")
print(new_dset)

     miles per gallon  cylinders  displacement horsepower  weight  \
0                18.0          8           307        130    3504
1                15.0          8           350        165    3693
2                18.0          8           318        150    3436
3                16.0          8           304        150    3433
4                17.0          8           302        140    3449
..                ...        ...           ...        ...     ...
393              27.0          4           140         86    2790
394              44.0          4            97         52    2130
395              32.0          4           135         84    2295
396              28.0          4           120         79    2625
397              31.0          4           119         82    2720

     acceleration vehicle_id
0            12.0  C-1689780
1            11.5  B-1689791
2            11.0  P-1689802
3            12.0  A-1689813
4            10.5  F-1689824
..            ...        ...
393          15.6  F-1694103
394          24.6  V-1694114
395          11.6  D-1694125
396          18.6  F-1694136
397          19.4  C-1694147

[398 rows x 7 columns]

In [128]:
data_threshold_horsepower = new_dset.query("miles per gallon >= 20")

SyntaxError: invalid syntax (<unknown>, line 1)

<font size = "4">

Pretty scary looking error message...basically, it doesn't like the space (variable names can't have spaces in Python)

We've seen the double quote (") and the single quote (')

To the left of your 1 key is the backtick/grave accent (`). Need to use this

In [ ]:
# next line causes error
# data_threshold_horsepower = new_dset.query("miles per gallon >= 20")

# this next line is fine
data_threshold_horsepower = new_dset.query("`miles per gallon` >= 20")
print(data_threshold_horsepower)

<font size = "4">

**Exercise:** Subset the data, gathering all cars with exactly 8 cylinders and mpg $\ge$ 25.

In [ ]:
# Your solution here

<font size = "4">

**Practice with other data sets**

**Exercise (coffee):** Subset to stores with `competitor_density_500m` >= 8 and a `customer_review_rating` of 5.0.

In [ ]:
# Your solution here

<font size = "4">


**Exercise (carlsen):** Subset to Blitz games (`format`) that Magnus Carlsen lost (`result`).

In [ ]:
# Your solution here

<font size = "4">

**Exercise (netflix):** Define `start_year = 2015` and `end_year = 2020`. Use those global variables to get titles released between those years (inclusive).

In [ ]:
# Your solution here

<font size = "4">

**Exercise (social):** Subset to students who sleep less than 5 hours or use social media more than 10 hours a day.

In [ ]:
# Your solution here

## <span style="color:red"> VII. Application: Visualizing Subsets of the Data </span>

<font size = "4">

List of unique categories

In [ ]:
# Use pd.unique() to extract a numpy array with the unique elements in that column

array_unique_cylinders = pd.unique(carfeatures["cylinders"])
print(array_unique_cylinders)
print(type(array_unique_cylinders))

<font size = "4">

Compute two overlapping plots

In [ ]:
# If we call plt.scatter() twice to display two plots
# To display all plots simultaneously we include plt.show() at the very end.
# The idea is that the graphs are stacked on top of each other

df_8 = carfeatures.query("cylinders == 8")
df_4 = carfeatures.query("cylinders == 4")

plt.scatter(x = df_8["weight"],y = df_8["acceleration"])
plt.scatter(x = df_4["weight"],y = df_4["acceleration"])
plt.legend(labels = ["8","4"],
           title  = "Cylinders")

plt.xlabel("Weight")
plt.ylabel("Acceleration")
plt.show()

# Note: If we put plt.show() in between the plots, then the results will
# be shown on separate graphs instead.

<font size = "4">

Compute plots by all categories

In [ ]:
# Compute number of unique categories
list_unique_cylinders = pd.unique(carfeatures["cylinders"])

# Use a for loop to plot a scatter plot between "weight" and "acceleration"
# for each category. Each plot  will have a different color

for category in list_unique_cylinders:
    df   = carfeatures.query("cylinders == @category")
    plt.scatter(x = df["weight"], y = df["acceleration"])
    
# Add labels and a legends    
plt.xlabel("Weight")
plt.ylabel("Acceleration")
plt.legend(labels = list_unique_cylinders,
           title  = "Cylinders")
plt.show()

<font size="4">

**Exercise:** Compute a histogram of "mpg" by cylinder count for cars with 4, 6, and 8 cylinders.Here is what it might look like (using a fake dataset):

<img src="data_raw/fake_histogram.png" alt="drawing" width="400"/>


You can make the histograms transparent by adjusting ```alpha``` in

```python
    plt.hist(x = ..., alpha = 0.5)
```

In [ ]:
# your code here

<font size = "4">


**Exercise (social):** Loop over the unique values of `Primary_Platform` and make a scatter plot of `Daily_Usage_Hours` vs. `Sleep_Duration_Hours`, one color per platform. Add axis labels and a legend.

In [ ]:
# your answer here

<font size = "4">

**Exercise (carlsen):** Plot overlapping histograms of `opponent_rating` for Blitz games and Rapid games. Add a legend and use `alpha` to make them transparent.

In [ ]:
# your answer here

<font size = "4">

**Exercise (netflix):** Plot overlapping histograms of `release_year` for Movies and TV Shows (`type`). Add a legend.

In [ ]:
# your answer here

<font size = "4">

**Exercise (coffee):** Use `pd.unique()` to find the categories of `order_method`. Then use a loop to make a scatter plot of `discount_voucher_pct` vs. `daily_cups_sold`, one color per order method, with a legend.

In [ ]:
# your answer here